return {
  {
    "neovim/nvim-lspconfig",
    opts = function(_, opts)
      opts.format.timeout_ms = 10000
      -- opts.servers.emmet_ls = {
      --   capabilities = require("cmp_nvim_lsp").default_capabilities(),
      --   filetypes = {
      --     "html",
      --     "pug",
      --     "javascript",
      --     "javascriptreact",
      --     "svelte",
      --     "typescript",
      --     "typescriptreact",
      --     "vue",
      --     "rust",
      --   },
      -- }
      opts.servers.tailwindcss = {
        filetypes = {
          "aspnetcorerazor",
          "astro",
          "astro-markdown",
          "blade",
          "clojure",
          "django-html",
          "htmldjango",
          "edge",
          "eelixir",
          "elixir",
          "ejs",
          "erb",
          "eruby",
          "gohtml",
          "haml",
          "handlebars",
          "hbs",
          "html",
          "html-eex",
          "heex",
          "jade",
          "leaf",
          "liquid",
          "markdown",
          "mdx",
          "mustache",
          "njk",
          "nunjucks",
          "php",
          "razor",
          "slim",
          "twig",
          "css",
          "less",
          "postcss",
          "sass",
          "scss",
          "stylus",
          "sugarss",
          "javascript",
          "javascriptreact",
          "reason",
          "rescript",
          "typescript",
          "typescriptreact",
          "vue",
          "svelte",
          -- "rust",
        },
        init_options = {
          userLanguages = {
            eelixir = "html-eex",
            eruby = "erb",
            rust = "html",
          },
        },
      }
    end,
  },
}
